### PR TITLE
Format flashcard seed data to JSON

### PR DESCRIPTION
**Pull request by StevieIsmagic**

### CODE REVIEW

**Comment by wlharvey4** [comment]
Can you change the main attributes to card_front: {object}, card_back: {object} so that we can put in different stuff as needed.  Right now the object can be like question: string and answer: string.

**Comment by StevieIsmagic** [comment]
Made modifications @wlharvey4 . How about now?

**Comment by wlharvey4** [comment]
Looking good, but can you make the value of the FrontCard an object also: <"FrontCard":"{"item":"what you have"}> so that we can add things easily if necessary? Not sure what else would go there, but it would be easier if it was an object to begin with.

**Comment by StevieIsmagic** [comment]
Third time's a charm! @wlharvey4

**Comment by wlharvey4** [comment]
Looks perfect; let's merge

**Pull request merged**
